######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 13 22:08:00 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/tapion/projects/doniAbrechnung/. .

# Input
HEADERS += MainForm.h
SOURCES += main.cpp MainForm.cpp
